spring:
  application:
    name : urlShortener

  data:
    mongodb:
      host: localhost
      port: 27017
      database: url_shortener_db

#redis config properties
  redis:
    host: localhost
    port: 6379
    password:

url:
  base: http://localhost:8080/
